os: linux
language: python
cache: pip
python:
 - 2.7
 - 3.4
 - 3.5
 - 3.6
 - 3.7
 - 3.8
 - nightly
install:
 - pip install --upgrade pip
 - pip install pipenv
 - pipenv install
 - pipenv shell
script:
 - coverage run setup.py test
after_success:
 - coveralls
